import = ["/Users/kampanosg/.config/alacritty/themes/themes/baitong.toml"]
live_config_reload = true
"window.dynamic_title" = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 13.5

[font.bold]
family = "JetBrainsMono Nerd Font Propo"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Propo"

[font.normal]
family = "JetBrainsMono Nerd Font Propo"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
